name: CI Build

on: push

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Toolchains
        id: cache-toolchains
        uses: actions/cache@v3
        with:
          key: cache-key-${{ hashFiles('configure.sh') }}
          restore-keys: |
            cache-key-${{ hashFiles('configure.sh') }}
          path: |
            ./toolchains
      - name: Install Development Environment
        run: arch -x86_64 brew install ninja meson
      - name: Configuration
        if: ${{ steps.cache-toolchains.outputs.cache-hit != 'true' }}
        run: arch -x86_64 ./configure.sh
      - name: Build
        run: |
          arch -x86_64 meson setup --cross-file build-win64.txt --native-file build-osx.txt build
          arch -x86_64 meson compile -C build
      - name: Tar
        run: tar -zcf artifacts.tar.gz build/src
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts.tar.gz