name: CI Build

on: push

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Toolchains
        id: cache-toolchains
        uses: actions/cache@v3
        with:
          key: cache-key-${{ hashFiles('configure.sh') }}
          restore-keys: |
            cache-key-${{ hashFiles('configure.sh') }}
          path: |
            ./toolchains
      # - name: Setup x86 Development Environment
        # run: arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install Development Environment
        run: brew install ninja meson
        shell: arch -x86_64 zsh -e {0}
      - name: Configuration
        if: ${{ steps.cache-toolchains.outputs.cache-hit != 'true' }}
        run: ./configure.sh
        shell: arch -x86_64 zsh -e {0}
      - name: Build
        run: |
          meson setup --cross-file build-win64.txt --native-file build-osx.txt build
          meson compile -C build
        shell: arch -x86_64 zsh -e {0}
      - name: Tar
        run: tar -zcf artifacts.tar.gz build/src
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts.tar.gz